name: Run Cargo Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86-64 configurations
          - os: ubuntu-latest
            gc-features: "generational"
            backend: "backend-x86-64"
          - os: ubuntu-latest
            gc-features: "compacting"
            backend: "backend-x86-64"
          - os: ubuntu-latest
            gc-features: "mark-and-sweep"
            backend: "backend-x86-64"
          # macOS ARM64 configurations
          - os: macos-latest
            gc-features: "generational"
            backend: "backend-arm64"
          - os: macos-latest
            gc-features: "compacting"
            backend: "backend-arm64"
          - os: macos-latest
            gc-features: "mark-and-sweep"
            backend: "backend-arm64"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Rust tests with features
        run: |
          RUST_BACKTRACE=1 cargo test --features ${{ matrix.gc-features }},${{ matrix.backend }} --release -- --test-threads=1

      - name: Run Beagle test suite
        if: always()
        run: |
          cargo run --features ${{ matrix.gc-features }},${{ matrix.backend }} --release -- test --ctrf ctrf-report.json resources/

      - name: Publish test results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
